# Generated by Django 3.2.5 on 2021-08-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_chek'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalTime', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='chek',
        ),
    ]
