# Generated by Django 3.2.5 on 2021-08-24 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_exertime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerTime',
        ),
    ]
