# Generated by Django 3.2.5 on 2021-08-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_delete_exertime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setno', models.IntegerField()),
                ('exert', models.IntegerField()),
                ('breakt', models.IntegerField()),
                ('totalt', models.IntegerField()),
            ],
        ),
    ]
